spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tatianarincon96/dh-gitconfig
          default-label: main

server:
  port: 8888
